#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <env>"
  echo "Example: $0 dev"
  exit 1
fi

ENV_NAME="$1"
shift

CONFIG="${ENV_NAME}.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" --plugin-dir "${BASEDIR}/.plugins"
