###################
### MY PROGRAMS ###
###################

$terminal = ghostty 
$terminal-bg = ghostty --config-file=~/.config/ghostty/background
$fileManager = dolphin
$menu = rofi -show drun
$torrent = rofi-cuff
$browser = brave
$mail = thunderbird

# Background apps
$bg-fetch = $terminal-bg --font-size=8 --title=bg-fetch -e zsh -c "tput civis; sleep 1 & while true; do clear; fastfetch -c arch; sleep 60; done"
$bg-cava = $terminal-bg --font-size=8 --title=bg-cava -e cava
$bg-btop = $terminal-bg --font-size=8 --title=bg-btop -e btop
$bg-yazi = $terminal-bg --font-size=10 --title=bg-yazi -e yazi
