[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd ~/.dotfiles"
desc = "Go to ~/.dotfiles"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/Documents"
desc = "Go to ~/Documents"

[[mgr.prepend_keymap]]
on = [ "g", "c" ]
run = "cd ~/.config"
desc = "Go to ~/.config"

[[mgr.prepend_keymap]]
on = [ "g", "/" ]
run = "cd /"
desc = "Go to root directory"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = "<C-g>"
run = "plugin lazygit"
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = ["'", "s"]
run = "plugin what-size -- '--clipboard'"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = ["'", "r"]
run = 'search_do --via=fd . --args="--newer 1h"'
desc = "Find recently changed files"
